fix: The ruled lines of unmerged cells disappear
excella-core/excella-reports pull request #63
Opened 2023-08-02 07:03 UTC by enunu

`ImageParamParser`で結合していないセルの罫線が消える問題を修正しました。

2023-08-02 08:40 UTC, enunu commented
期待値のnullと実測値の空を同一視して、スキップすることで後続のスタイルなどのチェックが行われなくなってしまう問題があるのでお待ちを・・再度、方針を検討します。

2023-08-02 23:35 UTC, enunu commented
上記のコメントについて、 26f98ed 時点でexpectedがnullかつactualがnullの場合に早期returnを行っているため、この条件下においてスタイルのチェックは行われない。また、expectedがnullの場合にスタイルの取得が出来ない。これらの理由より、今回の修正の範疇にないと判断しました。

2023-08-06 03:31 UTC, maruTA-bis5 commented on src/test/resources/org/bbreak/excella/reports/tag/ImageParamParserTest.xls
ImageParamParserTest.xls, ImageParamParserTest,xlsx, ImageParamParserTest_expected,xls, ImageParamParserTest_expected.xlsx の4ファイルについて、どのような意図を持って、どのように変更したのかを教えてもらえますか?

2023-08-06 08:16 UTC, enunu commented on src/test/resources/org/bbreak/excella/reports/tag/ImageParamParserTest.xls
https://github.com/excella-core/excella-reports/issues/62#issuecomment-1661171677 に基づいて、ファイルの差し替えおよび各シートのカーソルの調整を行いました。

2023-08-06 12:57 UTC, maruTA-bis5 requested changes

2023-08-06 23:15 UTC, enunu commented on src/test/resources/org/bbreak/excella/reports/tag/ImageParamParserTest.xls
すみません。各ImageParamParserTestのExcelファイルのシート1を確認したところ、罫線がないものになっていました。正しいものに差し替えを行い、ImageParamParserTest.javaを実行後、出力ファイルから罫線が消えていないことを確認しました。

2023-09-15 00:57 UTC, maruTA-bis5 requested changes
時間が空いてしまいすみませんが、1点コメントの修正をお願いします。

2023-09-15 00:57 UTC, maruTA-bis5 commented on src/test/java/org/bbreak/excella/reports/ReportsTestUtil.java
> +        // 期待値において、セル結合していないものはnullとなる。
`checkCell`自体は今回修正を必要とした箇所以外からも呼ばれますが、この書き方だと"セル結合していない"という条件を満たせば常にnullになるように感じてしまいます。
適当な表現を検討してもらえますか? 次の行だけで十分そうならこの説明を削っても良いかもしれません。

2023-09-25 00:08 UTC, maruTA-bis5 approved these changes

2023-09-25 03:49 UTC, merged